print("Hello, GitHub! I made changes.") 
print("This is my second line in example.py") 
print("Line 1: Hello, GitHub!") 
print("Line 2: This is my second update.") 
print("Line 3: Learning Git is fun!") 
print("Line 4: I am pushing 10 lines.") 
print("Line 5: Using echo command to add.") 
print("Line 6: Git tracks changes efficiently.") 
print("Line 7: Commit messages should be clear.") 
print("Line 8: Always check git status before pushing.") 
